baseURL = "http://example.org/"
languageCode = "en-us"
title = "LibreOffice Asia League"
theme = "libreoffice-asia-league"

[params]
    description = "The spirit of collaboration from Asian Community. We meet, work, and do execelent contributions to grow up LibreOffice in Asia."